Trevorghess/brackets
kevinreedy/shuffio pull request #211
Opened 2020-09-15 21:41 UTC by trevorghess

This PR enables the bracket view and landing page for the 2020 Bracket Challenge. Does not enable bracket selection functionality.

app/views/bracket/index.html.erb needs link to sign up page

2020-09-15 22:08 UTC, kevinreedy requested changes
A few quick changes

2020-09-15 22:08 UTC, kevinreedy commented on app/assets/stylesheets/bracket.scss
> +body {font-family: 'IBM Plex Mono', monospace;;background: url("http://picjumbo.com/wp-content/uploads/HNCK2189-1300x866.jpg") no-repeat #FFFFFF;background-size: cover;min-height: 100%;margin: 0;}
Is this going to change the font for the whole page when viewing the bracket? (think header and footer)

2020-09-15 22:08 UTC, kevinreedy commented on app/assets/stylesheets/bracket.scss
> +body {font-family: 'IBM Plex Mono', monospace;;background: url("http://picjumbo.com/wp-content/uploads/HNCK2189-1300x866.jpg") no-repeat #FFFFFF;background-size: cover;min-height: 100%;margin: 0;}
Let's bring this asset into `app/assets` in case it goes away on us

2020-09-15 22:08 UTC, kevinreedy commented on app/controllers/bracket_controller.rb
> +    @tournament = Tournament.last
Hmm... we'll need to revisit this when the backed is ready, but good for now.

2020-09-15 22:08 UTC, kevinreedy commented on app/views/bracket/current.html.erb
> +            <li class="team team-top"><%= @tournament.tournament_groups[0].tournament_rounds.last.matches[0].home_team.display_name %><span class="vote-count"><%= @tournament.tournament_groups[0].tou
let's update `vote-count` to `score or similar` for future us's sake

2020-09-15 22:08 UTC, kevinreedy commented on app/views/layouts/bracket.html.erb
> +<!DOCTYPE html>
It doesn't look like there's a need for a full new layout here. Let's not make one, so we don't have multiple places to change when we need to make an update.

2020-09-15 22:08 UTC, kevinreedy commented on db/schema.rb
> -    t.integer "color_change_after_frame"
whoops, how'd my unmerged branch slip in there...

2020-09-15 23:04 UTC, trevorghess commented on app/assets/stylesheets/bracket.scss
> +body {font-family: 'IBM Plex Mono', monospace;;background: url("http://picjumbo.com/wp-content/uploads/HNCK2189-1300x866.jpg") no-repeat #FFFFFF;background-size: cover;min-height: 100%;margin: 0;}
Good call out. Fixing this in an upcoming commit.

2020-09-15 23:04 UTC, trevorghess commented on app/assets/stylesheets/bracket.scss
> +body {font-family: 'IBM Plex Mono', monospace;;background: url("http://picjumbo.com/wp-content/uploads/HNCK2189-1300x866.jpg") no-repeat #FFFFFF;background-size: cover;min-height: 100%;margin: 0;}
Asset was unneeded, removed.

2020-09-15 23:05 UTC, trevorghess commented on app/controllers/bracket_controller.rb
> +    @tournament = Tournament.last
👍

2020-09-15 23:10 UTC, trevorghess commented on app/views/bracket/current.html.erb
> +            <li class="team team-top"><%= @tournament.tournament_groups[0].tournament_rounds.last.matches[0].home_team.display_name %><span class="vote-count"><%= @tournament.tournament_groups[0].tou
Fixing

2020-09-15 23:58 UTC, kevinreedy commented on app/views/bracket/index.html.erb
> +    <%= link_to "Slow down! We're not ready just yet, #{current_user.first_name}!", "javascript:;", class:"btn btn-primary btn-lg btn-block disabled" %>
you should throw a default value here, either `#{current_user.first_name} || 'Friend'` or we can add a method to models/user to do the same. happy if this goes into this PR or another, but we should have it for sure.

2020-09-15 23:59 UTC, kevinreedy approved these changes

2020-09-16 03:46 UTC, kevinreedy approved these changes

2020-09-16 03:46 UTC, merged